### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by Maltavius** [EventGhost/EventGhost#415]
**Describe the bug**
Since the start of October my Python script that talks to my Home Assistant server doesn't work.

**To Reproduce**
This is the code

```
import requests as req
headers = {'Authorization': 'Bearer <token>', 'content-type': 'application/json'}
url = 'http://<url>/api/services/mqtt/publish'
data = '{"payload": "ON", "topic":"pc/activity/state"}'
response = req.post(url, headers=headers, data=data)
print(response.text)

```
Error from EventGhost
```
         Traceback (most recent call last):
           Python script "3", line 5, in <module>
             response = req.post(url, headers=headers, data=data)
           File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\api.py", line 111, in post
             return request('post', url, data=data, json=json, **kwargs)
           File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\api.py", line 57, in request
             return session.request(method=method, url=url, **kwargs)
           File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\sessions.py", line 475, in request
             resp = self.send(prep, **send_kwargs)
           File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\sessions.py", line 606, in send
             history = [resp for resp in gen] if allow_redirects else []
           File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\sessions.py", line 179, in resolve_redirects
             **adapter_kwargs
           File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\sessions.py", line 585, in send
             r = adapter.send(request, **kwargs)
           File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\adapters.py", line 477, in send
             raise SSLError(e, request=request)
         SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```
**Expected behavior**
That the connection can be done.

**Additional context**
From what I can tell this has something to do with Let'sEncrypts Root Certificate Expiring
https://www.socialgrep.com/search?query=%2Fr%2Feventghost
https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

Is the Python version signed against an old Certificate or what is the problem?

**EventGhost version**
Software
Program Version: 0.5.0-rc6
Build Time: Mon, 24 Dec 2018 09:01:48
Python Version: Stackless Python 2.7.12 final 0
wxPython Version: 3.0.2.0

System
Operating System: Microsoft Windows 10 (Unknown Edition 101), 64-bit (build 19043)
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
RAM: 31.9 GB

**Comment by Maltavius** [comment]
The solution seems to be to get Python to trust the new Certificate ISRG Root X1
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by Gam3sFan** [comment]
Hi, did you fixed it? any advice how to do
thanks

**Comment by Maltavius** [comment]
I didn't

**Comment by Gam3sFan** [comment]
Oh :(

**Comment by kdschlosser** [comment]
you will need to start EventGhost as an Administrator. (right click EventGhost icon and click on "Run as Administrator" in the menu.

Make a new Python Script action and copy and paste the code below into that action. Then run the action. This will update the certificate file that is included with EventGhost. Report if it works or if it did not please. If it didn't any errors you get can you please copy them from the log and pate them into a reply here.

```python
import requests
import certifi

content = requests.get('http://curl.se/ca/cacert.pem').content

path = certifi.where()

with open(path, 'w') as f:
    f.write(content)

print('Certificate update complete!!')
```

**Comment by Maltavius** [comment]
> you will need to start EventGhost as an Administrator. (right click EventGhost icon and click on "Run as Administrator" in the menu.
> 
> Make a new Python Script action and copy and paste the code below into that action. Then run the action. This will update the certificate file that is included with EventGhost. Report if it works or if it did not please. If it didn't any errors you get can you please copy them from the log and paste them into a reply here.
> 
> ```python
> import requests
> import certifi
> 
> content = requests.get('http://curl.se/ca/cacert.pem').content
> 
> path = certifi.where()
> 
> with open(path, 'w') as f:
>     f.write(content)
> 
> print('Certificate update complete!!')
> ```

![image](https://user-images.githubusercontent.com/10133945/136100802-506cfd62-426f-4952-956d-e4847f3be14e.png)
```
   Traceback (most recent call last):
     Python script "5", line 4, in <module>
       content = requests.get('http://curl.se/ca/cacert.pem').content
     File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\api.py", line 71, in get
       return request('get', url, params=params, **kwargs)
     File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\api.py", line 57, in request
       return session.request(method=method, url=url, **kwargs)
     File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\sessions.py", line 475, in request
       resp = self.send(prep, **send_kwargs)
     File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\sessions.py", line 606, in send
       history = [resp for resp in gen] if allow_redirects else []
     File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\sessions.py", line 179, in resolve_redirects
       **adapter_kwargs
     File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\sessions.py", line 585, in send
       r = adapter.send(request, **kwargs)
     File "C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\adapters.py", line 477, in send
       raise SSLError(e, request=request)
   SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by kdschlosser** [comment]
not sure why certificates are being used for a non secure connection.

If you don't use EventGhost to connect to any webpages on the internet you can use this code in a Python Script action as well.
The action you make MUST be placed into the Autostart group. It MUST be placed as the very first item in the list.


```python
import sys
import requests


eg.globals.original_get = getattr(eg.globals, 'original_get', requests.get)

def get(url, params=None, **kwargs):
    if 'verify' not in kwargs:
        kwargs['verify'] = False

    return eg.globals.original_get(url, params=params, **kwargs)

sys.modules['requests'].get = get

```

**Comment by kdschlosser** [comment]
EG doesn't use the windows certificate store. It uses something different. The issue is being caused by a change to one of the root certificates and that new certificate is being used by websites and the certificate that EG has is an old one so it cannot verify the certificate.

**Comment by kdschlosser** [comment]
If you want to give it a go again to download a new version of the certificates instead of disabling verification of them (that is what is being done in the script above) you can use this code .


```python
import requests
import certifi

content = requests.get('http://curl.se/ca/cacert.pem', verify=False).content

path = certifi.where()

with open(path, 'w') as f:
    f.write(content)

print('Certificate update complete!!')
```

**Comment by Maltavius** [comment]
> If you want to give it a go again to download a new version of the certificates instead of disabling verification of them (that is what is being done in the script above) you can use this code .
> 
> ```python
> import requests
> import certifi
> 
> content = requests.get('http://curl.se/ca/cacert.pem', verify=False).content
> 
> path = certifi.where()
> 
> with open(path, 'w') as f:
>     f.write(content)
> 
> print('Certificate update complete!!')
> ```

Sadly no dice.

```

Import Cert
   C:\Program Files (x86)\EventGhost\lib27\site-packages\requests\packages\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
     InsecureRequestWarning)
   Traceback (most recent call last):
     Python script "6", line 8, in <module>
       with open(path, 'w') as f:
   IOError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\EventGhost\\lib27\\python27.zip\\certifi\\cacert.pem'
```

**Comment by Maltavius** [comment]
Yes, I also run as Administrator. Still doesn't work.

![image](https://user-images.githubusercontent.com/10133945/136468745-62c47dc9-49fd-49dc-8fe0-e11ca4570e93.png)

![image](https://user-images.githubusercontent.com/10133945/136468721-6b785c47-41ed-4c28-9d46-035036a5d510.png)

**Comment by kdschlosser** [comment]
OK I see where the problem is..

> DST Root CA X3 will expire on September 30, 2021

and the cacert.pem 
> generated at Thu Sep 30 03:12:05 2021 GMT

LOL. would figure.

I have a linux VM set up. Let me update Firefox on it and generate a cacert.pem file. You will have to change your script and drop the new pem file into your EventGhost directory. I will give you the new script once I make the file.

**Comment by kdschlosser** [comment]
ok change the script at the top of the autostart group to the code below
Download the attached file and unzip it to  `C:\Program Files (x86)\EventGhost\lib27` overwrite if a file already exists.

restart EG

```python
import os
os.environ['REQUESTS_CA_BUNDLE '] = 'C:\\Program Files (x86)\\EventGhost\\lib27\\cacert.pem'
```

[cacert.zip](https://github.com/EventGhost/EventGhost/files/7308465/cacert.zip)

**Comment by Maltavius** [comment]
> ok change the script at the top of the autostart group to the code below Download the attached file and unzip it to `C:\Program Files (x86)\EventGhost\lib27` overwrite if a file already exists.
> 
> restart EG
> 
> ```python
> import os
> os.environ['REQUESTS_CA_BUNDLE'] = 'C:\\Program Files (x86)\\EventGhost\\lib27\\cacert.pem'
> ```
> 
> [cacert.zip](https://github.com/EventGhost/EventGhost/files/7308465/cacert.zip)

Thanks!
This worked
I just put the os.environ in my "Import Cert" script at the top of Autostart.
Do I need to leave it there for every time or will this solve it permanently?

Maybe a new release of EventGhost with a proper cacert would be in order?

**Comment by kdschlosser** [comment]
Ok I let both of those projects know they need to update the file.

I can write a script that will check once a day to see if the script that Mozilla has is changed or not. That's about the best that I can do. I am pretty much at the mercy of curl and how quickly they update the file. You would think that they monitor what Mozilla has since they use the database in Firefox to build the file they use.  

Maybe they didn't know that Mozilla generated the same file.. dunno. 

https://github.com/curl/curl/issues/7836

Glad we got it sorted for the moment. I am going to put some thought into how I am going to go about writing an automatic download of the file.

**Comment by bloodsyphon** [comment]
For the PushBullet addon, it has its own cacert.pem file stored in C:\ProgramData\EventGhost\plugins\PushBullet\lib\websocket__0440 that you need to update. May be true with other addons as well. Check in the plugin directory.
