### ISSUE TITLE
Traceback on cFunctions import

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#57]
I am not sure if i am missing something but this happens on any version of the source i build.

C:\Python27>python C:/Users/Administrator/Desktop/EventGhost-master/_build/Build
.py
WARNING: Can't release to GitHub until you do the following:
    $ git config --global github.user <your github username>
    $ git config --global github.token <your github token>
To create a token, go to: https://github.com/settings/tokens

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/EventGhost-master/_build/Build.py", line
164, in <module>
    MyBuilder().Start()
  File "C:\Users\Administrator\Desktop\EventGhost-master\_build\builder\__init__
.py", line 163, in Start
    from Tasks import TASKS
  File "C:\Users\Administrator\Desktop\EventGhost-master\_build\builder\Tasks.py
", line 122, in <module>
    from builder.BuildDocs import BuildChmDocs, BuildHtmlDocs  # NOQA
  File "C:\Users\Administrator\Desktop\EventGhost-master\_build\builder\BuildDoc
s.py", line 30, in <module>
    import eg
  File "C:\Users\Administrator\Desktop\EventGhost-master\eg\__init__.py", line 9
0, in <module>
    import Core  # NOQA
  File "C:\Users\Administrator\Desktop\EventGhost-master\eg\Core.py", line 125,
in <module>
    Init.InitPathsAndBuiltins()
  File "C:\Users\Administrator\Desktop\EventGhost-master\eg\Init.py", line 147,
in InitPathsAndBuiltins
    import cFunctions
ImportError: DLL load failed: %1 is not a valid Win32 application.

C:\Python27>

**Comment by blackwind** [comment]
You're running a 64-bit version of Python, which we don't support at this time. Both this and #56 can be resolved by building with the 32-bit version.
