### ISSUE TITLE
Traceback on importing a duplicate module

### ISSUE THREAD

**Issue by kdschlosser** [EventGhost/EventGhost#82]
Not sure if this is my system or EG but after install I get this Traceback and the tree doesn't load. I do have Python 2.7 32 installed and that is the only interperter installed. I saw in a forum post about it using the path to the libs of the Python installation. so it could be that and it's trying to use that version of Crypto so I am going to uninstall it from Python to see if that solves it.

Unhandled exception in WorkerThread <EventThread>:
Callers stack:
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "wx\_core.pyc", line 16766, in <lambda>
Traceback (most recent call last) (0.5.0-beta1):
  File "C:\Program Files (x86)\EventGhost\eg\Classes\ThreadWorker.py", line 253, in __DoOneEvent
    self.HandleAction(action)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\ThreadWorker.py", line 140, in HandleAction
    action()
  File "C:\Program Files (x86)\EventGhost\eg\Classes\ThreadWorker.py", line 324, in __call__
    self.returnValue = self.func(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\EventThread.py", line 75, in StartSession
    actionThread.Func(actionThread.StartSession, 120)(filename)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\ThreadWorker.py", line 324, in __call__
    self.returnValue = self.func(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\ActionThread.py", line 86, in StartSession
    eg.document.Load(filename)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\Document.py", line 323, in Load
    root = self.RootItem(self, node)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\RootItem.py", line 47, in __init__
    eg.Password.SetDatabaseContent("")
  File "C:\Program Files (x86)\EventGhost\eg\__init__.py", line 45, in __getattr__
    mod = __import__("eg.Classes." + name, None, None, [name], 0)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\Password.py", line 26, in <module>
    from Crypto.Cipher import AES
  File "build\bdist.win32\egg\Crypto\Cipher\AES.py", line 50, in <module>
  File "build\bdist.win32\egg\Crypto\Cipher\_AES.py", line 7, in <module>
  File "build\bdist.win32\egg\Crypto\Cipher\_AES.py", line 3, in __bootstrap__
  File "pkg_resources\__init__.pyc", line 68, in <module>
    t

**Comment by kdschlosser** [comment]
That sure did fix it. So it defaults to the Python installation instead of it's own for installed Libs.

**Comment by blackwind** [comment]
> so it could be that and it's trying to use that version of Crypto so I am going to uninstall it from Python to see if that solves it.

Make sure to exhaust all troubleshooting steps before reporting next time.

> So it defaults to the Python installation instead of it's own for installed Libs.

It shouldn't. Open the Python Shell in EventGhost (Shift+Ctrl+I) and issue these commands:

```
>>> import sys
>>> sys.path
```

That's the order in which the paths are searched. If your Python folders come before your EventGhost folders, that's a bug that should be reported.

**Comment by kdschlosser** [comment]
when i was almost done typing the bug report the thought of what it could be popped into my head. and some of my python paths are before EG and some are after.

here is a screen shot

![python path](https://cloud.githubusercontent.com/assets/10932297/17646708/90fa47f6-6192-11e6-9905-d1a30e343e8b.png)

**Comment by blackwind** [comment]
Weird. I'll take a closer look.

**Comment by blackwind** [comment]
I'm guessing it's your configuration, as I'm not seeing anything in the code that would cause this. Hit Ctrl+N, Shift+Ctrl+~, Shift+Ctrl+I, and see if `sys.path` still contains the egg entries.

**Comment by kdschlosser** [comment]
i am assuming you want me to do those key combinations while in the shell from inside of EG. and if that is the case the output is exactly the same.

**Comment by blackwind** [comment]
Well, I'm all out of ideas, then. I suggest you uninstall Python 2.7, remove `C:\Python27`, and reinstall it. The next time you want to build EventGhost, use `python Build.py --make-env` first so you don't end up with such a wonky build environment.
